//
//  sessionsViewController.m
//  AgileAndBeyond
//
//  Created by Derek VerLee on 1/27/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "mainFilterSelectionMenu.h"
#import "sessionListViewController.h"


@implementation mainFilterSelectionMenu 

// functions for "building" the table view

// We'll just hard code the section titles, otherwise it ends up being in memory twice,
// plus any data structures.

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 3;      
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    switch (section) {
		case 0 : return 1 ; // All 
		case 1 : return 3 ; // By Difficulty 
		case 2 : return 3 ; // by technology
		default: return 0 ; 
		 // TODO error/assert andor do something consistant for "code should not be reached
	}
}

-(NSString*)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
	switch (section) {
		case 0 : return @"All"; 
		case 1 : return @"By Difficulty"; 
		case 2 : return @"By Technology";
		default: return @"";	
	     // TODO error/assert andor do something consistant for "code should not be reached
	}
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    
    static NSString *CellIdentifier = @"Cell";
	
	// we use the variable "cell" to hold the tablecell object to operate on
	// first, the dequeueReusable.. call sees if the cell already exists
	
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
	
	// if cell isn't nil, we've just fetched it from cache so don't recreate
	
	if (cell != nil) return cell;  // just abort here
	
	// This varient of the line generated by xcode appears in O'Rielly book,p224
	cell = [[[UITableViewCell alloc] initWithFrame:CGRectZero reuseIdentifier:CellIdentifier] autorelease];
	
	
	
	switch ([indexPath indexAtPosition:0]) // switch for which section
	{
			// section ALL 
		case 0 :  
			switch ([indexPath indexAtPosition:1]) { // switch by position within section 0 ("All")
				case 0 :
					cell.textLabel.text = @"All"; 
					cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;
					break;
					
			}
			break;
			
			
			// section By Difficulty
		case 1 : 
			switch ([indexPath indexAtPosition:1]) {
				case 0 : 
					cell.textLabel.text = @"Beginner"; 
					cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;	
					break;
				case 1 : 
					cell.textLabel.text = @"Intermediate"; 
					cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;	
					break;
				case 2 : 
					cell.textLabel.text = @"Advanced"; 
					cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;	
					break;
					
					
			}
			break;
			
			// section By Technology
		case 2 :  
			switch ([indexPath indexAtPosition:1]) {
				case 0 : 
					cell.textLabel.text = @"Java"; 
					cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;	
					break;
				case 1 : 
					cell.textLabel.text = @"All"; 
					cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;	
					break;
				case 2 : 
					cell.textLabel.text = @"Other"; 
					cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;	
					break;
			}
			break;
	}
	
	
	return cell;
}


- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath 
{

  sessionListViewController* filteredListView = nil;
	
  switch ([indexPath indexAtPosition:0]) // switch for which section
    {
      // section ALL 
    case 0 :  
      switch ([indexPath indexAtPosition:1]) { // switch by position within section 0 ("All")
      case 0 :
	filteredListView = [[sessionListViewController alloc] initWithNibName:@"sessionListViewController" bundle:nil];
	[self.navigationController pushViewController:filteredListView animated:YES];
	[filteredListView release];
	break;
					
      }
      break;
			
			
      // section By Difficulty
    case 1 : 
      switch ([indexPath indexAtPosition:1]) {
      case 0 : 
	break;
      case 1 : 
	break;
      case 2 : 
	break;
					
					
      }
      break;
			
      // section By Technology
    case 2 :  
      switch ([indexPath indexAtPosition:1]) {
      case 0 : 
     	break;
      case 1 : 
	break;
      case 2 : 
	break;
      }
      break;
    }
	
}	
@end
